apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ksbz5zrjo-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:66a0b72eb8c667b22d80c73902e950c769c48cef@sha256:f1b2362f87f6fe8b4948bf4bf18996f40c5180218eaf67e28c47ef6c71da2f8b
          name: container-image
